#Q7) Display the Id and Name of the Product ordered after “2021-10-05”. 

SELECT Q.PRO_ID, P.PRO_NAME FROM PRODUCT AS P
INNER JOIN
(
	SELECT S.PRO_ID FROM SUPPLIER_PRICING AS S
	INNER JOIN
	(SELECT `ORDER`.* FROM `ORDER` WHERE `ORDER`.ord_date>"2021-10-05") as O
	ON S.PRICING_ID = O.PRICING_ID
)AS Q 
ON P.PRO_ID = Q.PRO_ID;
